### ISSUE TITLE
Interface - Page_animals

### ISSUE THREAD

**Issue by LucasPaulo001** [Gerencia-de-configuracao-e-mudancas/projeto-final-sithcodex#2]
## Tasks 

- [x] Adição do conteúdo
- [x] Estilização do conteúdo
- [x] Responsividade da página
