### ISSUE TITLE
Interface - Page_gangues

### ISSUE THREAD

**Issue by LucasPaulo001** [Gerencia-de-configuracao-e-mudancas/projeto-final-sithcodex#3]
## Tasks

- [x] Adição de conteúdo
- [x] Estilização do conteúdo
- [x] Responsividade da página
